### ISSUE TITLE
Strange behavior with directory permissions

### ISSUE THREAD

**Issue by patrickdawson** [npm/node-tar#123]
I have the following file structure:

```
app
|--zipme
|   |--data (mode 777)
|   |   |--foo.txt (mode 777)
```

If I ran the follwing code
```javascript
"use strict";

const tar = require("tar");

tar.c({
    gzip: true,
    file: "arch.tgz",
}, ["zipme"])
.then(() => tar.x({
    cwd: "x",
    file: "arch.tgz",
}))
.then(() => console.log("done!"))
    .catch(err => console.log(err));
```
the directory x/zipme/data has the mode 755 (probably because of the process umask).
When I run this code again without deleting the output dir (x/zipme) then the data directory gets the mode 777. Is this indented? 
I expected the mode of the directory to be mode 777 the first time I run this code.

The same is not true for files. The mode stays unchanged on 755 regardless of how often I run this code.

Is there a way to have the modes of the tar source replicated in the output directory without changing the umask of the process?

**Comment by isaacs** [comment]
Ah, this is interesting.

Short answer/workaround: call `process.umask(0)` to get this to work how you want immediately.  The fix is possible, but a little annoying.  Here's why this is happening.

If you want to create a dir, tar will check to see if the thing is already there, and if not, it says "ok, great, I'll just create it with the mode you want".  In this case, it's limited by the umask, so you get 0o755 (with the default unix umask of 0o22).

If the thing is already there, and already a directory, then it says "cool, don't have to create the thing", but if the mode doens't match, it calls fs.chmod.  However, `chmod` is _not_ limited by umask, so in this case, you get 0o777.

What it needs to do is _also_ check to see if the current process umask is going to block it from creating in the mode it wants, and then chmod after creation in those cases.  Only calling things like `fs.chmod` when absolutely necessary is a significant performance boost.

If you feel like digging into the code, the place to start poking around is `lib/unpack.js` in the `[CHECKFS]`, `[MAKEFS]` and `[DIRECTORY]` methods.  The actual fs.mkdir is called in `lib/mkdir.js`.

**Comment by isaacs** [comment]
Moved to #135 with plan of action and terser explanation of the problem so that it's easier to act on.  Closing this debugging issue.  Thanks for bringing it up!
