### ISSUE TITLE
Refactore API in PATCH version???

### ISSUE THREAD

**Issue by ivankravets** [npm/node-tar#129]
Hi,

We've received a lot of complaints that our @platformio IDE installer stopped work. It stays on unpacking project examples (tar.gz)... See https://github.com/platformio/platformio-atom-ide/blob/develop/lib/installer/helpers.js#L115

I see the latest commit: https://github.com/npm/node-tar/commit/ce83d2470527d04033a60c7c04ef73b3c7daf8df

> Unpack: do not emit 'end' 

What do you do in PATCH version? I'm not keen in this npm-machinery and npm SemVer policy. Is it normal that package changes API in PATCH version?

P.S I've just rolled back to the previous version (3.1.8) which works well https://github.com/platformio/platformio-atom-ide/commit/35ab27cc2d0738b632a17f978ac5e68c41d4a01f

**Comment by isaacs** [comment]
The stream in question is a writable stream, not a readable stream.  It should not have ever emitted `end` because you are not reading data out of it.  That event was hazardous to use, because it would emit when the unpacked files were done being written, but _not_ before they were actually closed and finished being touched.

Listen on `close` instead of `end`.  It's better, and avoids race conditions.  I apologize for letting the bug linger there long enough for you to grow attached to it.

**Comment by ivankravets** [comment]
Why did you close this issue? The problem is not linked with end/close. Please take a look at the SUBJECT.

Is it normal in Node.JS world that developer changes API in PATCH version? Not saying about MINOR...
