### ISSUE TITLE
8GB per file limit? Also, how to flatten directory structure

### ISSUE THREAD

**Issue by dandanknight** [npm/node-tar#131]
Hi, I'm trying to tar files larger than 8GB, but I'm having no luck. Same as with tar-stream/tar-fs. Does node-tar adopt the ustar format same as the others? Is there a way round this, or do I need start from scratch and spawn a tar from shell?

Also, whilst I'm here, is there a way of creating a TAR without the directory structure? For instance
```
/some/dir/foo.jpg
/some/other/dir/bar/jpg
```
Should be packed, list, and unpack (without using the `--strip-components` option) as...
```
foo.jpg
bar.jpg
```
Thanks

**Comment by isaacs** [comment]
Huh.  Yeah, that seems to be flaking out somewhere near the end.  Looks like it finishes properly, but the file is truncated.

```
$ dd if=/dev/zero of=10gb bs=1024 count=0 seek=$[1024*1024*10]
0+0 records in
0+0 records out
0 bytes transferred in 0.000016 secs (0 bytes/sec)

$ ls -lh 10gb
-rw-r--r--  1 isaacs  staff    10G Aug 15 00:32 10gb

$ node -e 'require("./").create({file:"10gb.tar"},["10gb"])'

$ la 10gb.tar
-rw-r--r--  1 isaacs  staff  10737420800 Aug 15 00:36 10gb.tar

$ tar tvf 10gb.tar
-rw-r--r--  1 isaacs 20 2748779069472 Aug 15 00:32 10gb
tar: Truncated input file (needed 2748779069952 bytes, only 2748779067904 available)
tar: Error exit delayed from previous errors.
```

**Comment by isaacs** [comment]
As for your second question, no, there's no easy way to do this.  With the builtin `tar(1)`, you could do a `tar cf out.tar -C some/dir foo.jpg -C some/other/dir bar.jpg`, but you'd have to list out each file one by one.  Since there's no `onentry` or `map` method in `tar.create`, the only way I could see to do that out of the box today would be repeated calls to `tar.replace` or `tar.update` to append entries to the archive.

It'd be nice to add a way to filter or mutate files on the way into the archive, but that should get its own issue :)

**Comment by dandanknight** [comment]
The issue I found with tar-fs/tar-stream was that they used the ustar TAR format, which has an individual file limit of 8GB. Not sure if this is a similar issue?

More [here](https://www.gnu.org/software/tar/manual/html_section/tar_68.html)

**Comment by isaacs** [comment]
node-tar uses PAX extended headers if the file is too big to fit in the 8gb size limit.  There might be some bug in how it's doing that, but it _is_ successfully putting a file in the tarball that's much larger than 8gb.  It's _not_ getting the full 10gb, though.  Dropping a 2 mb off the end for some reason.

So it's not the 8gb limit in this case.  Definitely something else going on.  And it's not dropping the trailing tar EOF footer, because that'd be 1MB, not 2.

Curiouser and curiouser...

**Comment by isaacs** [comment]
Oh, also, in the xstar format (used by most ustar tar systems), you _can_ have files larger than 8gb, by encoding the number as a base-256 tuple instead of an octal string.  So you don't even need PAX extended headers for that.  It supports sizes in the range of an 11-byte unsigned int, which is bigger than any hard drive on earth currently.  (64-bit is only an 8 byte range.)
