### ISSUE TITLE
large file Array buffer allocation failed at new ArrayBuffer 

### ISSUE THREAD

**Issue by hoythan** [npm/node-tar#138]
electron
```
fs.createReadStream(filePath).pipe(
    tar.x({
        C: 'C:\\Users\\hoyt\\Desktop\\'
    })
)
```

error log
```
Uncaught RangeError: Array buffer allocation failed
```
nodejs:8.4.0
npm:5.3.0

**Comment by hoythan** [comment]
filesize : 4gb

**Comment by tgds** [comment]
+1, but filesize was around 50GB. 
It's **line 205 write-entry.js**: `buf = Buffer.allocUnsafe(length)`

Since the WriteEntry class is an event emitter, this should be also wrapped in try/catch and emitted as an error event. Currently, it will always throw you uncaught errors. There's multiple Buffer.alloc calls that error handling to be fixed throughout the project.

**Comment by isaacs** [comment]
No longer an issue, I believe.
