### ISSUE TITLE
Replace is not replacing file

### ISSUE THREAD

**Issue by bishbashbosh123** [npm/node-tar#149]
Hi,
I am noticing that I cannot _replace_ a file in a tar using `tar.replace` or `tar.update`; instead the file to be updated/replaced is simply appended again.
```
const archivePath  = 'test.tar'
const fileName = 'test.jpg'
tar.c({ file: archivePath }, [fileName])
.then(_ => tar.r({ file: archivePath }, [fileName]))
.then(_ => tar.r({ file: archivePath }, [fileName]))
```
If I open up the tar file in 7zip the file is in there three times.  Am I missing something?

tar@4.0.2
Windows 10
Node 6.11.4

Thanks

**Comment by isaacs** [comment]
`tar r` just appends the file to the end.  Since tar files are "last entry wins" when unpacked, this means that the later entry overwrites the one before it.  Node-tar works exactly the same as `tar(1)` in this regard.  There's no way to actually replace the entry in-place without repacking the whole file, since the length may have changed.
