### ISSUE TITLE
noDirRecurse not working as expected

### ISSUE THREAD

**Issue by juanda99** [npm/node-tar#153]
Shouldn't noDirRecurse archive files of the directories not just the empty directory?
`tar.c({ noDirRecurse: true}, [dir1, dir2]).then(_ =>`

Something like:
```
dir1/fil1 - ok
dir1/file2 - ok
dir1/subdir1 - no
dir1/subdir1/file11 - no
```

**Comment by isaacs** [comment]
This is working as intended.

The `noDirRecurse` flag means "do not recurse into _any_ directories".  So that means, any directories passed in as a file argument will not be recursed into.  Instead, they'll be added to the archive as an empty directory.  When using this flag, you must explicitly name each file you want added to the archive.

This is exactly the same as the behavior of the `-n` flag passed to `tar(1)`.

It sounds like what you want is a filter on any sub-directories of the dirs passed in.  For arbitrary/custom behavior you're requesting, I recommend using a filter function:

```js
tar.c({
  file: 'out.tar',
  filter: (path, stat) => {
    if (stat.isDirectory() && path.split('/').length > 1)
      return false
    else
      return true
  }
}, ['dir1', 'dir2'])
```
