### ISSUE TITLE
Use xz with tar

### ISSUE THREAD

**Issue by Adobe-Android** [npm/node-tar#167]
Hey, I'd like to use xz instead of gzip and I was wondering if there is a straightforward way of doing this.

**Comment by isaacs** [comment]
I don't know how to use xz in node, but you can pipe the tar.create() stream through whatever kind of compression algorithm you want.  I include builtin support for gzip because it's very popular, and bundled with node directly.  I'm not interested in adding other compression methods to this module directly, but if you run into issues using it with an xz implementation, I'd be happy to take a look.

**Comment by Adobe-Android** [comment]
Could I have you take a look at something sometime tomorrow? I'll be able
to send it in around 10 AM? How's that?

**Comment by Adobe-Android** [comment]
Actually, after doing some more benchmarks I'm going to use Google's Brotli
instead. It's insane! I can basically get the compression ratio of xz, but
do it WAY faster or choose to compress it slightly more than xz-utils can.
