### ISSUE TITLE
[Unrelated] Fastest way to detect truncated tar files

### ISSUE THREAD

**Issue by julien-f** [npm/node-tar#234]
Hi there,

This is an unrelated question so feel free to close this ticket if that bothers you :slightly_smiling_face: 

I'm looking for a way to detect truncated tar files without having to read them entirely.

My use case: big tar files on network storage, looking for a way to detect which one appears truncated to be able to clean them automatically.

The files contains a lot of 1 MiB files which makes reading only headers and skipping the data portion not efficient enough.

If you have any idea, it would be much appreciated.

Best regards,

**Comment by isaacs** [comment]
It's not a guarantee, but a heuristic I'd try would be to look for files where the file size is not an even multiple of 512, and the last kb is not all null bytes.

It IS only advisory that a tar file end with at least a kb of nulls, but every tar implementation out there does this, so it's at least a good indicator that you should look at those ones first.

If the file is not an even multiple of 512 bytes, then it either has some junk appended/prepended,  or it's damaged in some other way (most likely being that the file is cut off in the middle).

Of course, if the file happens to be cut off at a block boundary, and maybe that last file just had a KB of null bytes at the end, then it'll result in a false negative.  And since a tar that ends without 2 blocks of nulls is allowed, that would technically still be a valid tarball.

You can expect that 1 out of every 512 truncated files will be cut off at a block boundary (assuming it's random), and of those, probably very few happen to contain a file with a kb of nulls at the truncation point, so I'd reckon that it'd find well over 99.9% of truncated files (much more depending on the occurrence of files containing large strings of nulls).  If you have a corpus with a million truncated files, just the 512 byte check would find all but 1954 of them.

A better approach (if it's possible) is to calculate an integrity checksum value when the tarball is created, and stash that alongside it, and then check it again when the file is used.  This is what npm does, and it's a much more efficient way to handle potentially damaged files.

Happy hunting!

**Comment by isaacs** [comment]
Actually, this check is even better than I thought at first.  If the average file size is 1MiB, and _every_ file in every archive is full of nulls (_why are you storing so many null files??_ this seems really redundant lol), and _no_ files have extended pax headers, then there's a 1/3 chance that a file truncated at a byte boundary is truncated such that it ends with a kb of nulls.

So  even in that boundary condition, you still find all but 651 out of a million truncated files, or a 99.935% success rate.  Not too shabby.

**Comment by julien-f** [comment]
Thank you so much for this detailed answer!

Indeed, it looks like a good heuristic, I'm going to check if that works with the files I have :slightly_smiling_face: 

> A better approach (if it's possible) is to calculate an integrity checksum value when the tarball is created, and stash that alongside it, and then check it again when the file is used. This is what npm does, and it's a much more efficient way to handle potentially damaged files.

This is not possible because I cannot to read the whole files (hundreds of GiB).

**Comment by julien-f** [comment]
Thank you for your help, the results appear to be quite good :tada:

**Comment by julien-f** [comment]
@isaacs Thank you so much for this heuristic, it works very well :slightly_smiling_face: 

Unfortunately, I still have another issue: some files are compressed with gzip (deflate algorithm), and I am l looking for a way to validate them, again without having to read the whole file.

I've read [the file format](https://www.onicos.com/staff/iz/formats/gzip.html) and I don't see any way to do it, any ideas would be greatly appreciated :slightly_smiling_face:
