### ISSUE TITLE
[QUESTION] Is it possible to cache file positions within the tar for faster read access?

### ISSUE THREAD

**Issue by benjaffe** [npm/node-tar#280]
# What / Why
I'm working on an electron app that handles media files that are packaged in a wrapper file format. (My file format is actually just a .tar under the hood.) These tar files contains many json and media files, and can be many GB in size.

I'm noticing that extracting files that live near the end of the .tar take a long time to extract, even if they are small files. It seems like any time I access a file, node-tar runs through the entire tar file until it reaches the desired file inside.

I'm wondering if there's any way to cache the tar file structure so I can random-access files more quickly. The tar files don't really change, other than sometimes having things appended to the end. I did see the notes about `linkCache`, `statCache`, and `readdirCache`, but looking through the library, it seems those aren't referenced during extraction operations... unless I'm missing something obvious.

Any thoughts? Also, incredible work on this library. It's been so stable and reliable! <3

## Where
* n/a

## Who
@benjaffe

## References
* n/a

**Comment by isaacs** [comment]
Thanks for the <3

I've thought a lot about ways to make random-access possible in tar files.  There isn't really a straightforward way to do it, just given the structure of a tarball, since it's designed to be used in an append-only "last entry wins" sort of way.  (It is designed for Tape ARchives, after all, where appends are cheap, but random access is intolerably slow and can actually destroy the media if done too often.)

Since we do not often put tars on tapes these days, you _could_ (in theory) preserve some of the nice properties of tar files, but append a file index at the end of the archive after each write.  The structure could be something like:

```
[header] <-- first tar entry, offset=0
[body]
[body]
[header] <-- second entry, offset=512*3
...more entries...
[tar index header]
[tar index body]
[tar index footer block]
[1024 nulls] <-- tar EOF block
```

The `tar index header` would have a special type field, and potentially some other indications to say "this is the index of the files within the tarball".

The `tar index body block` would be 1 or more blocks, containing the data:

```
path = numeric offset from start of file
path2 = numeric offset
[null-padded to a multiple of 512 bytes]
```

Then the `tar index footer block` would contain the number of `tar index body` blocks that proceed it.  (In practice, I'd probably make this another special custom header type, with `size=0`, where some property in the header contains the number we care about.)

So, when reading a file, you could do the following:

1. Do a positioned read from position `filesize - 1536` (2*512 for the null EOF block, plus 512 for where we expect the tar index footer block to start.)
2. If the data found looks like a `tar index footer`, pull out the number from it.  That number is our `index size` (in blocks).  Do a read from position `filesize - 1536 - (index size + 1) * 512`, with length of `(index size + 1) * 512`.
3. Try to parse the result as a tar entry.  If it parses properly, and the `type` field in the header is our special value, then we parse the body as our random access index, and get the last offsets (or every offset) of every file in the archive.

Then, if we want to extract just one file, we can jump straight to it.  If we want to create a trimmed down archive that contains just the last entry for each path, we can read out all the entries and write them to a new archive file.  If these are operations you do often, on large archives that contain a lot of duplicate entries, then it could be a real time saver.  And it'd only take 2 additional read operations to do it.

To maintain the index, it'd be a fairly straightforward matter of always loading the index when we're about to append to a file (either with `tar.u` or `tar.r`), update the index value for any path we added, and then write it back at the end of the stream.

Reasons I did not do this:

1. It would never work on gzipped tars.  One reason the tar archive has been able to enjoy as much longevity as it has is that it compresses _so extremely well_ with gzip.  Nice orderly chunks, aligned in 512 byte boundaries, having tons of repetition and padding, and so on.
2. Even though the tar specification quite explicitly states that unknown file types should always be ignored, in practice many implementations complain or crash when encountering them.
3. So ok, let's say, we don't use a non-standard file type, we use a `PaxHeader` entries, which are technically allowed to contain any arbitrary key=value pairs.  But!  Even though the tar specification quite explicitly states that unknown PAX header keys should always be ignored, in practice many implementations complain or crash when encountering them.
4. Since npm package tarballs never live in an uncompressed state (we just stream them through gzip when we want to unpack them, the thing on disk is always a tgz), I have exactly zero use for this.
5. The chances of any other tar implementing this is in the "slim to none" range, for all the reasons listed (including this one).

If you want compressed files that support random access, I recommend using zip files, rather than tar.

**Comment by benjaffe** [comment]
Oh wow, thank you for the incredible reply, and that all makes complete sense! I'll instead try and be smarter about knowing what files I'll want before asking for them, so I can extract multiple files in one pass. For my project this might mean introducing a bit of inefficiency to batch extractions, but it'll save a ton of time for extracting from large files.

Thanks again for the detailed reply. :)
