### ISSUE TITLE
symbolic link gets corrupted

### ISSUE THREAD

**Issue by jfromaniello** [npm/node-tar#54]
Example:

```javascript
var request = require('request');
var tar = require('tar');
var zlib = require('zlib');

request('http://nodejs.org/dist/v0.12.1/node-v0.12.1-darwin-x64.tar.gz')
  .pipe(zlib.Gunzip())
  .pipe(tar.Extract({path: __dirname}));
```

Result:

```bash
» ls -lh node-v0.12.1-darwin-x64/bin
total 36328
-rwxr-xr-x  1 jose  staff    18M Mar 23 23:02 node
lrwxr-xr-x  1 jose  staff    73B Mar 23 23:02 npm -> /tmp/test-tar/lib/node_modules/npm/bin/npm-cli.js
```

It seems node-tar is resolving the sym link incorrectly and is missing some directories. 

If I rather use tar(1):

```bash
» wget http://nodejs.org/dist/v0.12.1/node-v0.12.1-darwin-x64.tar.gz
» tar -xzf node-v0.12.1-darwin-x64.tar.gz
» ls -lh node-v0.12.1-darwin-x64/bin
total 36328
-rwxr-xr-x  1 jose  wheel    18M Mar 23 23:02 node
lrwxr-xr-x  1 jose  wheel    38B Mar 23 23:02 npm -> ../lib/node_modules/npm/bin/npm-cli.js
```

Questions:

1.  Am I doing something wrong?
2.  Is there a way to prevent node-tar changing relative paths to absolute?

**Comment by limulus** [comment]
I ran into this too. It seems to be a bug introduced in 2.0.0. So a potential workaround is to downgrade to 1.0.3 for the time being.

**Comment by othiym23** [comment]
This behavior is the consequence of a fix for a [security issue](https://github.com/npm/node-tar/commit/a5337a6cd58a2d800fc03b3781a25751cf459f28) that had been lurking in npm for a long time. Unfortunately, allowing symlinks inside tarballs to point outside the extraction destination allows tarballs to overwrite files to which the tarball should have no access under certain circumstances, and so `node-tar` normalizes them.

It's possible we could add a flag to `node-tar` along the lines of `unsafeSymlinks` to get back the old behavior, but it would have to be done in such a way that it's disabled by default for users of the package, because of the underlying security problem.

**Comment by isaacs** [comment]
@othiym23 I think that's a good idea, but in this case, we are actually not linking to something outside of the tarball, and it's being resolved to the wrong absolute thing anyway.

The symlink is something like:

```
foo/bin/npm -> ../lib/some/path
```

So, even if we resolve it, it should resolve to `/extract/path/foo/lib/some/path`, but instead, it's going to `/extract/path/lib/some/path`, which is incorrect.

It looks like we're doing `path.join(extractPath, path.join('/', linkPath))`, and we ought to be doing something like `path.join(extractPath, path.join('/', path.join(entryPath, linkPath)))` or something.  Ie, first resolve the linkPath against the entryPath, *and then* make it absolute.

Also, we don't have to make it absolute if it doesn't end up linking outside of the extractPath.

**Comment by othiym23** [comment]
OK, I understand now. This is definitely on us to fix. Sorry for the false alarm.

**Comment by isaacs** [comment]
@jfromaniello Can you verify that this is fixed in 2.0.1?

**Comment by jfromaniello** [comment]
@isaacs It works perfectly now! 

Thank you both,

**Comment by limulus** [comment]
Can also confirm this fixes this issue. Thanks Forrest && Isaac! :)
