### ISSUE TITLE
strip option doesn't fix the target of symlinks

### ISSUE THREAD

**Issue by aredridel** [npm/node-tar#65]
Extracting a package with `foo/bin/a -> foo/bin/b`, with `{ strip: 1 }`, I get `bin/a -> foo/bin/b`

**Comment by isaacs** [comment]
This is working as designed, and as it works in tar(1).  Since symlinks are relative, a link at `foo/bin/a` to `foo/bin/b` would actually resolve to `foo/bin/foo/bin/b`.  When unpacking with strip=1, the `foo/bin/a` is unpacked to `bin/a` and now points at `bin/foo/bin/b` which is 1 dir less than it would've been without the strip option.
